#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Config"})
---
#@overlay/match missing_ok=True
destinations:
  - image: capabilities-controller-manager:latest
    newImage: #@ "{}/capabilities-controller-manager".format(data.values.registry)
    #@overlay/replace
    tags:
      - #@ data.values.image_tag
