#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Config"})
---
destinations:
  #@overlay/match by=overlay.subset({"image":"addons-controller:latest"})
  - newImage: #@ "{}/addons-controller".format(data.values.registry)
    #@overlay/replace
    tags: #@ data.values.tags
