---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: tkr-resolver-cluster-webhook:latest
    path: ../../../
    docker:
      build:
        file: pkg/v2/tkr/webhook/cluster/tkr-resolver/Dockerfile