#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Config"})
---
destinations:
  #@overlay/match by=overlay.subset({"image":"tkr-resolver-cluster-webhook:latest"})
  - newImage: #@ "{}/tkr-resolver-cluster-webhook".format(data.values.registry)
    #@overlay/replace
    tags: #@ data.values.tags
