#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Config"})
---
destinations:
  #@overlay/match by=overlay.subset({"image":"featuregates-controller-manager:latest"})
  - newImage: #@ "{}/featuregates-controller-manager".format(data.values.registry)
    #@overlay/replace
    tags: #@ data.values.tags
