---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-tkg-package-sa
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-pkg"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-tkg-package-cluster-role
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-pkg"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-tkg-package-cluster-rolebinding
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-pkg"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-tkg-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-tkg-package-sa
    namespace: tkg-system
