name: Build TKG repository bundle
on: [push]
jobs:
  build-tooling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish package-bundle-tooling
        run: |
          image_name=${TOOLING_CACHE_FROM}
          docker login --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}" "${{ secrets.REGISTRY_SERVER }}"
          make package-bundle-tooling
          docker image tag package-bundle-tooling:latest ${image_name}
          docker push ${image_name}
        env:
          DOCKER_BUILDKIT: 1
          TOOLING_CACHE_FROM: ${{ secrets.OCI_REGISTRY }}/package-bundle-tooling:latest

      - name: Build and publish package-repo-bundle-tooling
        run: |
          image_name=${TOOLING_CACHE_FROM}
          docker login --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}" "${{ secrets.REGISTRY_SERVER }}"
          make package-repo-bundle-tooling
          docker image tag package-repo-bundle-tooling:latest ${image_name}
          docker push ${image_name}
        env:
          DOCKER_BUILDKIT: 1
          TOOLING_CACHE_FROM: ${{ secrets.OCI_REGISTRY }}/package-repo-bundle-tooling:latest

  discover-packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        run: |
          make -C hack/tools yq
          matrix=$(hack/tools/bin/yq e -j -I=0 '.repositories.management.packages.[] | {"package-name": .name, "package-path": .path} | [.] | {"include": .}' packages/package-values.yaml)
          echo "::set-output name=matrix::${matrix}"

  check-packages:
    runs-on: ubuntu-latest
    needs: discover-packages
    steps:
      - name: Check list of packages
        run: |
          matrix='${{ needs.discover-packages.outputs.matrix }}'
          echo $matrix | jq .

  build-packages:
    runs-on: ubuntu-latest
    needs: [discover-packages, build-tooling]
    strategy:
      matrix: ${{ fromJson(needs.discover-packages.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch git tags
        run: git fetch --prune --unshallow --tags

      - name: Build and publish ${{ matrix.package-name }} package
        run: make build-package-dind
        env:
          PACKAGE_PATH: ${{ matrix.package-path }}
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}
          DOCKER_BUILDKIT: 1
          TOOLING_CACHE_FROM: ${{ secrets.OCI_REGISTRY }}/package-bundle-tooling:latest

      - name: Set permissions on artifact
        run: |
          sudo chmod 0644 "${{ matrix.package-path }}/bundle/.imgpkg/images.yml"

      - name: Upload ${{ matrix.package-name }} image lock
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package-name }}-artifact
          path: "${{ matrix.package-path }}/bundle/.imgpkg/images.yml"

  build-package-repo:
    runs-on: ubuntu-latest
    needs: [discover-packages, build-packages, build-tooling]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch git tags
        run: git fetch --prune --unshallow --tags

      - name: Download all image lock files
        uses: actions/download-artifact@v3

      - name: Copy image lock files to proper places
        run: |
          matrix='${{ needs.discover-packages.outputs.matrix }}'
          echo $matrix | jq ".include[] | .[]" | xargs -n2 sh -c 'mkdir -p "$1/bundle/.imgpkg/" && cp "$0-artifact/images.yml" "$1/bundle/.imgpkg/images.yml"'

      - name: Build and publish TKG repository bundle
        run: make build-package-repo-bundle-dind
        env:
          PACKAGE_REPOSITORY: "management"
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}
          DOCKER_BUILDKIT: 1
          TOOLING_CACHE_FROM: ${{ secrets.OCI_REGISTRY }}/package-repo-bundle-tooling:latest

      - name: Set permissions on artifact
        run: |
          sudo find build -type d -exec chmod 755 {} \;
          sudo find build -type f -exec chmod 644 {} \;

      - name: Upload PackageRepository artifact
        uses: actions/upload-artifact@v3
        with:
          name: PackageRepository
          path: |
            build/package-repo-bundles/management/tanzu-framework-*.yaml
            build/package-repo-bundles/management/tanzu-framework-*.tar.gz

