name: Build TKG composite package
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish TKG composite package
        run: make build-package-dind
        env:
          PACKAGE_PATH: "packages/management/tkg"
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}
