name: Build TKG repository bundle
on: [push]
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Matrix
        id: set-matrix
        env:
          PACKAGE_REPOSITORY: "tkgrepo"
        run: |
          make -C hack/tools yq
          matrix=$(hack/tools/bin/yq e -j -I=0 '.tkgrepoPackageRepository.packages.[] | {"package-name": .name, "package-path": .path} | [.] | {"include": .}' packages/package-values.yaml)
          echo "::set-output name=matrix::${matrix}"

  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix | jq .

  build-packages:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish ${{ matrix.package-name }} package
        run: make docker-build-package-dind
        env:
          PACKAGE_PATH: ${{ matrix.package-path }}
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}

      - name: Upload ${{ matrix.package-name }} image lock
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.package-name }}-artifact
          path: "${{ matrix.package-path }}/.imgpkg/images.yml"

  build-package-repo:
    runs-on: ubuntu-latest
    needs: [matrix, build-packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download all image lock files
        uses: actions/download-artifact@v3

      - name: Copy image lock files to proper places
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix | jq ".include[] | .[]" | xargs -n2 sh -c 'cp "$0-artifact/images.yml" "$1/.imgpkg/images.yml"'

      - name: Build and publish TKG repository bundle
        run: make docker-build-package-repo-bundle-dind
        env:
          PACKAGE_REPOSITORY: "tkgrepo"
          PACKAGE_VALUES_FILE: "packages/package-values.yaml"
          REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          OCI_REGISTRY: ${{ secrets.OCI_REGISTRY }}
